name: Go

on:
  push:
    branches:
     - main
  pull_request:
    branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Dependencies
        run: sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev xorg-dev libasound2-dev -y

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - run: mkdir executables

      - name: Build Linux
        run: GOOS=linux GOARCH=amd64 go build -o executables/linux/gogogopher

      - name: Build Windows
        run: GOOS=windows GOARCH=amd64 go build -o executables/windows/gogogopher.exe

      - uses: actions/upload-artifact@v2
        with:
          name: Linux Executable
          path: executables/linux/gogogopher
      - uses: actions/upload-artifact@v2
        with:
          name: Windows Executable
          path: executables/windows/gogogopher.exe

  build-mac:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - run: mkdir executables

      - name: Build Mac
        run: GOOS=darwin GOARCH=amd64 go build -o executables/darwin/gogogopher

      - uses: actions/upload-artifact@v2
        with:
          name: MacOS Executable
          path: executables/darwin/gogogopher
