name: Go

on:
  push:
    branches:
     - main
  pull_request:
    branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up OpenGl
        uses: openrndr/setup-opengl@v1.1

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - run: mkdir executables

      - name: Build Linux
        run: GOOS=linux go build -o executables/linux/gogogopher

      - name: Build Windows
        run: GOOS=windows go build -o executables/windows/gogogopher.exe

      - name: Build Mac
        run: GOOS=darwin go build -o executables/darwin/gogogopher

      - uses: actions/upload-artifact@v2
        with:
          name: Executables
          path: executables/
